# Generated by Django 2.0.3 on 2018-03-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('person', 'Normal user'), ('filterer', 'Filterer'), ('politician', 'Politician')], default='person', max_length=20),
        ),
    ]
