# Generated by Django 2.0.3 on 2018-03-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterers', '0002_auto_20180310_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterertopolitician',
            old_name='accepted_by_filterer',
            new_name='accepted',
        ),
        migrations.RemoveField(
            model_name='filterertopolitician',
            name='accepted_by_politician',
        ),
    ]
